### ISSUE TITLE
Adding support to mode-streaming

### ISSUE THREAD

**Issue by wbarnha** [lqhuang/mode-ng#1]
Thanks for maintaining this project. I've been [working on getting mode-steaming to support Python 3.11](https://github.com/faust-streaming/mode/pull/20) and it's been giving me quite a challenge. I'd be happy to make a joint effort to pull your changes in and sunset support for versions of Python 3.9 and earlier, since our fork doesn't get much maintenance.

**Comment by lqhuang** [comment]
Ok, thanks for your attention!

I will test my fork under Python 3.11 release recently. Do you have roadmap/deadlines?

**Comment by wbarnha** [comment]
We don't have any particular roadmap or deadlines right now for mode-streaming. Would you have any interest in being a maintainer for mode-streaming? We're looking for more help with the project and we could use more hands. I'll check internally before sending an invitation.

**Comment by lqhuang** [comment]
I'm glad to be a maintainer. It's definitely fine to improve project and codes, except delaying the roadmap for `faust-streaming` due to lack of time, LOL.

I use mode framework in my work, so I will keep improving `mode-ng` at least until my owned services are end of life.  For `mode-streaming`, I think my principle rule is to keep back forward compatibility for `faust`. It sounds good?

**Comment by wbarnha** [comment]
My idea was to modify the requirements.txt file so that `mode-streaming<=0.2.1` is the last version for older Python versions. Something like:
```
mode-streaming<=0.2.1; python_version <= '3.9`
mode-streaming>0.2.1; python_version > '3.9`
```
`mode-streaming` hasn't been functionally updated in some time and I know it's responsible for some bugs in `faust-streaming`, but I don't have the bandwidth to investigate. No system anywhere is running Faust in 3.11 so I'd value your input, so long as Faust functionality isn't negatively imapcted :smile:. The `asyncio` library changed significantly in 3.10 and 3.11 so I'm hoping you could have some insight on where to improve where Ask Solem left off.

**Comment by lqhuang** [comment]
No problem 😂 I'm so willing to help!

**Comment by wbarnha** [comment]
We have sent the invite to add you as a maintainer. Join the Slack via https://join.slack.com/t/fauststream/shared_invite/enQtNDEzMTIyMTUyNzU2LTIyMjNjY2M2YzA2OWFhMDlmMzVkODk3YTBlYThlYmZiNTUwZDJlYWZiZTdkN2Q4ZGU4NWM4YWMyNTM5MGQ5OTg so we can coordinate releases
